BuildingType.DWELLING=building_dwelling
BuildingType.RICE_FARM=building_rice_farm
BuildingType.RICE_PADDY=building_rice_paddy
BuildingType.WOODCUTTERS_HUT=building_woodcutters_hut
BuildingType.MINE=building_mine
BuildingType.SMITHY=building_smithy
BuildingType.WORKSHOP=building_workshop
BuildingType.MARKET=building_market
BuildingType.GUARD_POST=building_guard_post
BuildingType.TEMPLE=building_temple
NaturalFeature.FOREST=feature_forest
ResourceType.RICE=icon_resource_rice
ResourceType.TIMBER=icon_resource_timber
ResourceType.TOOLS=icon_resource_tools
ResourceType.LUXURY_GOODS=icon_resource_luxury_goods
PolicyType.AGRICULTURAL_EXPANSION=icon_policy_agricultural_expansion
PolicyType.MILITARY_PROTECTION=icon_policy_military_protection
PolicyType.CRAFTSMEN_PRODUCTION=icon_policy_craftsmen_production
